[[plugins]]
repo = 'altercation/vim-colors-solarized'
[[plugins]]
repo = 'aereal/vim-colors-japanesque'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'cohama/lexima.vim'
[[plugins]]
repo = 'vim-scripts/Flake8-vim'
[[plugins]]
repo = 'davidhalter/jedi-vim'
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'wlangstroth/vim-racket'
